version: '2'
services:
    courthouse:
        image: code-court
        restart: unless-stopped
        environment:
            - CODE_COURT_DB_URI=postgresql+psycopg2://codecourt:benpass@postgres/codecourt
        volumes:
            - ./courthouse_data:/tmp
        expose:
            - 9191

    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./nginx_data/conf.d:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80

    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=codecourt
            - POSTGRES_PASSWORD=benpass
            - POSTGRES_DB=codecourt
        # volumes:
        #     - ./postgres_data:/var/lib/postgresql/data
